color_theme = "tokyo-night"
theme_background = False
truecolor = True
force_tty = False
vim_keys = True
rounded_corners = True
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 1500
