#!/usr/bin/env bash
vol=$(pamixer --get-volume-human 2>/dev/null)
case "$vol" in
    muted)  printf '<fn=2>\uf026</fn> muted' ;;
    0%)     printf '<fn=2>\uf026</fn> 0%%' ;;
    [1-9]%|[1-3][0-9]%) printf '<fn=2>\uf027</fn> %s' "$vol" ;;
    *)      printf '<fn=2>\uf028</fn> %s' "$vol" ;;
esac
